### ISSUE TITLE
Reload after Login

### ISSUE THREAD

**Issue by GNSSYSTEMS-tg** [ElderByte-/ngx-jwt-auth#12]
Reloading the page immediately after login should be avoided or at least configurable.

**Comment by IsNull** [comment]
The issue should be resolved with the latest version `2.0.0-beta.15`.

It will only use a location redirect (which leads to a page refresh) when you manually specify an absolute redirect URL. By default, a local login will always result in a local router redirect.

@GNSSYSTEMS-tg Let me know if this works for you.

**Comment by GNSSYSTEMS-tg** [comment]
Fixed.
