### ISSUE TITLE
Support for Angular 5

### ISSUE THREAD

**Issue by GNSSYSTEMS-tg** [ElderByte-/ngx-jwt-auth#13]
Since Angular 5 was released yesterday, a migration might be required (e.g. operators for observables).

https://angular-update-guide.firebaseapp.com/

**Comment by IsNull** [comment]
Yes I think this migration is necessary in the long run - even though I find the new Syntax quite a step back. After-all, they adopted the syntax to fix the import issues with TS/Rx, which seems the wrong way around. But anyway, I think it has been decided.

From my understanding and also the resource you just posted, it is a SHOULD and not MUST as rx won't be able to drop the current syntax that fast. To that end, I think it should work - we only have to allow ng 5 in our peer dependencies.

A bigger issue is the old Http client required by the JWT library. I think we have to updated to their latest version to get rid of it as this module has been dropped.

We usually follow the latest frameworks closely, so Angular 5 will be on our radar.

**Comment by IsNull** [comment]
https://github.com/auth0/angular2-jwt/issues/442 😱 
As we only depend on the JWT decoding classes which actually have nothing to do with Angular to begin with, we can handle it ourself if the need arrises.

I will observe this for 1-2weeks but if there is no ETA on a release date we might have to solve it our own. The good news is that this JWT stuff is hidden behind this library and we can handle it as we see fit. 😄

**Comment by GNSSYSTEMS-tg** [comment]
Mh, now I'm a little disappointed on auth0 ... I thought, they'd be ambitious.

**Comment by GNSSYSTEMS-tg** [comment]
Btw. did you plan any milestones for `2.0`? I've got one or two suggestions on the code, but this can wait for `2.1`, since I require the enhancements in `master` for at least two productive projects ;) So I prefer a stable release for once.

**Comment by IsNull** [comment]
No actually I think we can release the current beta version as stable. That is, I will merge your PR tomorrow after some checks and then we settle on the current API for 2.0.

First my idea was to include the ng 5 and angular-jwt upgrades in 2.0 but since this would be an ETA of unknown time we go with this for 2.0. 

If all goes well, we can even upgrade to angular-jwt 1.0 and introduce ng 5 support without breaking the 2.0 API at all.

**Comment by GNSSYSTEMS-tg** [comment]
Ah, there's one thing that concerns me before the release though: #12 

I remember, you justified this with an issue in your application. Is it fixed now or does the idea of a configurable behavior sound good to you? For me it still breaks things...

**Comment by IsNull** [comment]
See PR #19
